/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library/index'
import { Route as AppLibrarySeriesIdIndexRouteImport } from './routes/_app/library/$seriesId/index'
import { Route as AppLibrarySeriesIdVolumeIdIndexRouteImport } from './routes/_app/library/$seriesId/$volumeId/index'
import { Route as AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport } from './routes/_app/library/$seriesId/$volumeId/$chapterId/index'
import { Route as AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport } from './routes/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrarySeriesIdIndexRoute = AppLibrarySeriesIdIndexRouteImport.update({
  id: '/library/$seriesId/',
  path: '/library/$seriesId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrarySeriesIdVolumeIdIndexRoute =
  AppLibrarySeriesIdVolumeIdIndexRouteImport.update({
    id: '/library/$seriesId/$volumeId/',
    path: '/library/$seriesId/$volumeId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdVolumeIdChapterIdIndexRoute =
  AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport.update({
    id: '/library/$seriesId/$volumeId/$chapterId/',
    path: '/library/$seriesId/$volumeId/$chapterId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute =
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport.update({
    id: '/library/$seriesId/$volumeId/$chapterId/$pageNumber',
    path: '/library/$seriesId/$volumeId/$chapterId/$pageNumber',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/library/$seriesId/$volumeId/$chapterId/': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/library/$seriesId': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/library/$seriesId/$volumeId/$chapterId': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/_app/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/_app/library/$seriesId/$volumeId/$chapterId/': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library/'
    | '/library/$seriesId/'
    | '/library/$seriesId/$volumeId/'
    | '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/library/$seriesId/$volumeId/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/library/$seriesId'
    | '/library/$seriesId/$volumeId'
    | '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/library/$seriesId/$volumeId/$chapterId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/library/'
    | '/_app/library/$seriesId/'
    | '/_app/library/$seriesId/$volumeId/'
    | '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/_app/library/$seriesId/$volumeId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/': {
      id: '/_app/library/$seriesId/'
      path: '/library/$seriesId'
      fullPath: '/library/$seriesId/'
      preLoaderRoute: typeof AppLibrarySeriesIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/': {
      id: '/_app/library/$seriesId/$volumeId/'
      path: '/library/$seriesId/$volumeId'
      fullPath: '/library/$seriesId/$volumeId/'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/$chapterId/': {
      id: '/_app/library/$seriesId/$volumeId/$chapterId/'
      path: '/library/$seriesId/$volumeId/$chapterId'
      fullPath: '/library/$seriesId/$volumeId/$chapterId/'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber': {
      id: '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      path: '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      fullPath: '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppLibrarySeriesIdIndexRoute: typeof AppLibrarySeriesIdIndexRoute
  AppLibrarySeriesIdVolumeIdIndexRoute: typeof AppLibrarySeriesIdVolumeIdIndexRoute
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  AppLibrarySeriesIdVolumeIdChapterIdIndexRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppLibrarySeriesIdIndexRoute: AppLibrarySeriesIdIndexRoute,
  AppLibrarySeriesIdVolumeIdIndexRoute: AppLibrarySeriesIdVolumeIdIndexRoute,
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute:
    AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute,
  AppLibrarySeriesIdVolumeIdChapterIdIndexRoute:
    AppLibrarySeriesIdVolumeIdChapterIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
